/*************************************************************************************************************
 * @name      AssetTypeEnumerator
 * @author      Ivanna Panchenko <ivanna@beIntelligent.nz>
 * @created      5 November 2021
 * @description    Salestrekker Wrapper Class
 * @testClass      N/A
 *
 * Changes (version)
 * -----------------------------------------------------------------------------------------------------------
 *         No.    Date      Author          Description
 *         ----  ------------  --------------------  ----------------------------------------------
 * @version    1.0    2021-11-05      Ivanna Panchenko      Creation of the class
 *
**************************************************************************************************************/
public enum AssetTypeEnumerator {
    owner_occupier_property_address,
    investment_property_address,
    vehicle_make_and_model,
    bank_accounts,
    home_contents,
    kiwisaver,
    superfund_institution,
    shares,
    other,
    balance_sheet
   
}