/*************************************************************************************************************
 * @name      BankAccountTypeEnumerator
 * @author      Ivanna Panchenko <ivanna@beIntelligent.nz>
 * @created      5 November 2021
 * @description    Salestrekker Wrapper Enum
 * @testClass      N/A
 *
 * Changes (version)
 * -----------------------------------------------------------------------------------------------------------
 *         No.    Date      Author          Description
 *         ----  ------------  --------------------  ----------------------------------------------
 * @version    1.0    2021-11-05      Ivanna Panchenko      Creation of the class
 *
**************************************************************************************************************/
public enum BankAccountTypeEnumerator {
    none ,
    savings_account,
    transaction_account,
    cheque_account,
    other_account
}