/*************************************************************************************************************
 * @name      HouseholdExpenseTypeEnumerator
 * @author      Ivanna Panchenko <ivanna@beIntelligent.nz>
 * @created      23 November 2021
 * @description    Salestrekker Wrapper Class
 * @testClass      N/A
 *
 * Changes (version)
 * -----------------------------------------------------------------------------------------------------------
 *         No.    Date      Author          Description
 *         ----  ------------  --------------------  ----------------------------------------------
 * @version    1.0    2021-11-23      Ivanna Panchenko      Creation of the class
 *
**************************************************************************************************************/

public enum HouseholdExpenseTypeEnumerator {
        //food_and_supermarket_coffees_lunches_takeaway_entertainment_domestic_holidays_gym_fees_sport_other_health_and_wellness_cigarettes_and_alcohol_clothing_shoes_and_accessories_hairdressing_and_grooming_phone_internet_and_pay_tv_media_streaming_and_subscription_services_gifts_and_celebrations_other_discretionary_expenses_recreational_vehicle_running_costs_pets_public_education_costs_private_education_costs_tertiary_and_vocational_education_childcare_child_or_spousal_maintenance_private_health_insurance_doctor_dentist_pharmacy_glasses_life_trauma_income_insurance_essential_vehicle_running_cost_public_transport_taxis_and_ride_share_commuting_airfares_essential_vehicle_insurance_current_rent_expense_ongoing_board_expense_primary_residence_running_costs_primary_residence_body_corp_secondary_residence_running_costs_secondary_residence_body_corp_investment_property_running_costs_investment_property_body_corp,
        food_and_supermarket,        
        coffees_lunches_takeaway,
        entertainment,
        domestic_holidays,
        gym_fees_sport_other_health_and_wellness,
        cigarettes_and_alcohol,
        clothing_shoes_and_accessories,
        hairdressing_and_grooming,
        phone_internet_and_pay_tv,
        media_streaming_and_subscription_services,
        gifts_and_celebrations,
        other_discretionary_expenses,
        recreational_vehicle_running_costs,
        pets,
        public_education_costs,
        private_education_costs,
        tertiary_and_vocational_education,
        childcare,
        child_or_spousal_maintenance,
        private_health_insurance,
        doctor_dentist_pharmacy_glasses,
        life_trauma_income_insurance,
        essential_vehicle_running_cost,
        public_transport_taxis_and_ride_share_commuting_airfares,
        essential_vehicle_insurance,
        current_rent_expense,
        ongoing_board_expense,
        primary_residence_running_costs,
        primary_residence_body_corp,
        secondary_residence_running_costs,
        secondary_residence_body_corp,
        investment_property_running_costs,
        investment_property_body_corp

}
