/*************************************************************************************************************
 * @name      LiabilityTypeInput
 * @author      Ivanna Panchenko <ivanna@beIntelligent.nz>
 * @created      18 November 2021
 * @description    Salestrekker Wrapper Class
 * @testClass      N/A
 *
 * Changes (version)
 * -----------------------------------------------------------------------------------------------------------
 *         No.    Date      Author          Description
 *         ----  ------------  --------------------  ----------------------------------------------
 * @version    1.0    2021-11-18      Ivanna Panchenko      Creation of the class
 *
**************************************************************************************************************/
public with sharing class LiabilityTypeInput {
    public LiabilityTypeEnumerator name { get; set; }
}