/*************************************************************************************************************
 * @name      LiabilityTypeEnumerator
 * @author      Ivanna Panchenko <ivanna@beIntelligent.nz>
 * @created      18 November 2021
 * @description    Salestrekker Wrapper Enum
 * @testClass      N/A
 *
 * Changes (version)
 * -----------------------------------------------------------------------------------------------------------
 *         No.    Date      Author          Description
 *         ----  ------------  --------------------  ----------------------------------------------
 * @version    1.0    2021-11-18      Ivanna Panchenko      Creation of the class
 *
**************************************************************************************************************/
public enum LiabilityTypeEnumerator {
    mortgage_loan,
    credit_card,
    overdraft,
    vehicle_loan,
    personal_loan,
    SMSF_loan,
    education_debt,
    other,
    balance_sheet
}