/*************************************************************************************************************
 * @name      PaymentFrequencyEnumerator
 * @author      Ivanna Panchenko <ivanna@beIntelligent.nz>
 * @created      24 November 2021
 * @description    Salestrekker Wrapper Class
 * @testClass      N/A
 *
 * Changes (version)
 * -----------------------------------------------------------------------------------------------------------
 *         No.    Date      Author          Description
 *         ----  ------------  --------------------  ----------------------------------------------
 * @version    1.0    2021-11-24      Ivanna Panchenko      Creation of the class
 *
**************************************************************************************************************/

public enum PaymentFrequencyEnumerator {
    none,
    weekly,
    fortnightly,
    monthly,
    quarterly,
    semiannual,
    annually
}