/*************************************************************************************************************
 * @name      PropertyTypeEnumerator
 * @author      Ivanna Panchenko <ivanna@beIntelligent.nz>
 * @created      5 November 2021
 * @description    Salestrekker Wrapper Enum
 * @testClass      N/A
 *
 * Changes (version)
 * -----------------------------------------------------------------------------------------------------------
 *         No.    Date      Author          Description
 *         ----  ------------  --------------------  ----------------------------------------------
 * @version    1.0    2021-11-05      Ivanna Panchenko      Creation of the class
 *
**************************************************************************************************************/
public enum PropertyTypeEnumerator {
  none,
  apartment_unit_flat,
  company_title_unit,
  duplex,
  fully_detached_house,
  holiday_home,
  holiday_rental,
  house_and_land ,
  licensed_builder_construction,
  owner_builder_construction,
  semi_detached_house,
  serviced_apartment,
  strata_title_unit,
  single_bedroom_less_than_fifty_sqm,
  townhouse,
  vacant_land ,
  villa
}